### ISSUE TITLE
Forward Keycloak Token Information sends wrong values

### ISSUE THREAD

**Issue by KevinHorvatin** [apiman/apiman-plugins#38]
This is my plugin configuration

![image](https://cloud.githubusercontent.com/assets/503610/10083974/78c5a71e-62c6-11e5-9213-87ec7d3fa56f.png)

This sends the following (this is just a snippet of the headers):
header | value
----------|---------
x-apiman-email | example-user
x-apiman-subject | example-user

these two values (and all values) are _example-user_

The keycloak attributes from the token are:
kc attribute | value
---------------|----------
email |  user@example.com
name | Example User

**Comment by msavy** [comment]
This was a bug in older versions of the plugin. Which one are you using?

**Comment by KevinHorvatin** [comment]
1.1.7.Final

**Comment by KevinHorvatin** [comment]
You are right - fixed in 1.1.8.Final
