### ISSUE TITLE
keycloak-oauth-policy looks for Bearer case-sensitively

### ISSUE THREAD

**Issue by KevinHorvatin** [apiman/apiman-plugins#39]
When looking for the bearer token in the Authorization header, the plugin will incorrectly perform a case-sensitive search.

The rfc for Authorization header states that the authentication scheme is case-insensitive.

see: http://www.ietf.org/rfc/rfc2617.txt, specifically section 1.2 which states -

_It uses an extensible, case-insensitive token to identify the authentication scheme_

**Comment by msavy** [comment]
Hmm, our Header map implementation is meant to be case insensitive. I'll look into this one tomorrow, thanks!

**Comment by msavy** [comment]
@EricWittmann please close this

**Comment by EricWittmann** [comment]
Is this not a bug?  Was it resolved?  I seem to recall a relevant commit with a change to compareIgnoreCase?

**Comment by msavy** [comment]
Yes, a fix was committed https://github.com/apiman/apiman-plugins/commit/2700e98fdf5ec61a0800002bfc3c253624811261

**Comment by EricWittmann** [comment]
OK thanks. :)
