### ISSUE TITLE
transformation-policy adds extra root node json to xml

### ISSUE THREAD

**Issue by Semprini** [apiman/apiman-plugins#61]
The root node shouldn't be inserted into response unless the JSON root is a list. This would allow the transform the other way to match. Taken from tests:

```
{ "PLANT": {
    "COMMON": "Bloodroot",
...}
```

json to xml starts with root node:

```
<root>
  <PLANT>
    <PRICE>$2.44</PRICE>
...
```

but no root node used when converting the other way:

```
<PLANT>
  <COMMON>Bloodroot</COMMON>
...
```

xml to json goes to:

```
{ "PLANT": {
    "COMMON": "Bloodroot",
...}
```

Looks like it's just a matter of changing the XML.toString in JsonToXmlTransformer.java to drop the root node argument if the source JSON does not have a list as root. Pull request submitted.

**Comment by msavy** [comment]
I believe this was fixed some time ago. Closing.
